### ISSUE TITLE
send data with space

### ISSUE THREAD

**Issue by ghost** [aZholtikov/ZHNetwork#2]
not work send data with space

trim on space.

Please change to uint8_t*

**Comment by aZholtikov** [comment]
Hello. I don't really understand where the problem is with space.

From the examples:
myNet.sendBroadcastMessage("Hello world!") works.
myNet.sendUnicastMessage("Hello world!", target) works.
myNet.sendUnicastMessage("Hello world!", target, true) works.

Show me some of your non-working code.

**Comment by ghost** [comment]
Не вылетело, на 30+ устройств ловлю судя по всему переполнение очереди и ребут с exceptionОтправлено с устройства Galaxy
-------- Исходное сообщение --------От: Alexey Zholtikov ***@***.***> Дата: 25.06.2023  13:57  (GMT+03:00) Кому: aZholtikov/ZHNetwork ***@***.***> Копия: PavelLazarevd ***@***.***>, Author ***@***.***> Тема: Re: [aZholtikov/ZHNetwork] send data with space (Issue #2) 
Hello. I don't really understand where the problem is with space.
From the examples:
myNet.sendBroadcastMessage("Hello world!") works.
myNet.sendUnicastMessage("Hello world!", target) works.
myNet.sendUnicastMessage("Hello world!", target, true) works.
Show me some of your non-working code.

**Comment by aZholtikov** [comment]
Наверное понял проблему. И она не в пробеле...
Иногда при большом количестве устройств (я это ловил начиная с 20-25+) в один прекрасный момент может начаться циклическая перезагрузка всех. Это происходит из-за так называемого "широковещательного шторма".
Предсказать момент невозможно. Может день, может и месяц.
В однопоточной программе для Ардуино я этого решить не смог. 

Сейчас медленно перевожу все проекты на чистый С с FreeRTOS на RTOS SDK 3.4 и ESP-IDF 5.0.
Ждите обновлений.

**Comment by ghost** [comment]
Сейчас медленно перевожу все проекты на чистый С с FreeRTOS на RTOS SDK 3.4 и ESP-IDF 5.0. 

так же начал миграцию (на esp8266 на rtos esp32 и так на RTOS даже на ардурино)своего умного дома суб и вск бегал с программатором перепрашивал +-40 устройств, после такого шторма, но судя по дебагу esp32 у меня есть отладчик там забивается очередь потом падает сеть ну и дальше сторож перегружает, к сожалению на 8266 не могу проверить нету дебагера адекватного, но что в 1 что во втором случае если смотреть память она тупо утекает и все падает, я тут либу немного поменял, ввел crc16 на пакеты что бы понимать побился покет или нет и перевел data c char на uint8 https://disk.yandex.ru/d/qGNjH8v2M1Zdcg

**Comment by aZholtikov** [comment]
Каждая новая маленькая версия этой библиотеки на С проверяется на утечки памяти. Ох и устал же я с этим бороться... Но потихоньку побеждаю... К концу года надеюсь победить.

P.S. В С++ библиотеке очередей нет проблем с утечкой, есть проблема с дефрагментацией кучи. Для ESP это равнозначно...

**Comment by ghost** [comment]
может ТГ? там удобней.

**Comment by aZholtikov** [comment]
ТГ?
