### ISSUE TITLE
Can I use delay()

### ISSUE THREAD

**Issue by crouse12** [aZholtikov/ZHNetwork#3]
When I use delay() to replace millis(), the program cannot work.
Is it possible for us to use delay()?

**Comment by aZholtikov** [comment]
No. These are completely different functions.

millis() simply counts down the time from the start of the program.
delay() stops it for the specified time.

**Comment by crouse12** [comment]
Thank for your response.
Second question: Is it possible for us to use mqtt or web server when I use this esp-now library?

**Comment by aZholtikov** [comment]
Of course.
For an example, see https://github.com/aZholtikov/ESP-NOW-Gateway
