### ISSUE TITLE
Transmission problem

### ISSUE THREAD

**Issue by Sebiferi** [aZholtikov/ZHNetwork#6]
Hello,
I am having problem with transfer after every SEARCH_REQUEST from transmitter.
I want to ask for help.

**ZHNetwork version: 1.42**
**Receiver: ESP32 [MAC:78218491E47C  ]**
**Transmitter: esp8266 [MAC:8CAAB50E7E3E ] or ESP32 (same error)**
**Arduino IDE 2.2.1**

**Transmitter serial output:**
`13:11:30.556 -> DELIVERY_CONFIRM_RESPONSE message from MAC 78218491E47C to MAC 8CAAB50E7E3E via MAC 78218491E47C received.
13:11:30.581 -> Message to MAC 78218491E47C ID 56802 delivered 47481 micros
13:11:31.509 -> CHECKING ROUTING TABLE... Routing to MAC 78218491E47C not found. Target is 78218491E47C.
13:11:31.541 -> UNICAST_WITH_CONFIRM message from MAC 8CAAB50E7E3E to MAC 78218491E47C via MAC 78218491E47C added to queue.
13:11:31.541 -> UNICAST_WITH_CONFIRM message from MAC 8CAAB50E7E3E to MAC 78218491E47C via MAC 78218491E47C sended. Status OK.
13:11:31.573 -> DELIVERY_CONFIRM_RESPONSE message from MAC 78218491E47C to MAC 8CAAB50E7E3E via MAC 78218491E47C received.
13:11:31.573 -> Message to MAC 78218491E47C ID 0 delivered 50518 micros
13:11:32.024 -> SEARCH_REQUEST message from MAC 8CAAB50E7E3E to MAC 78218491E47C added to queue.
13:11:32.056 -> Message to MAC 78218491E47C ID 32512 ---undelivered--- 517772 micros
13:11:32.056 -> SEARCH_REQUEST message from MAC 8CAAB50E7E3E to MAC 78218491E47C via MAC FFFFFFFFFFFF sended. Status OK.
13:11:32.056 -> SEARCH_RESPONSE message from MAC 78218491E47C to MAC 8CAAB50E7E3E received.
13:11:32.511 -> CHECKING ROUTING TABLE... Routing to MAC 78218491E47C not found. Target is 78218491E47C.
13:11:32.563 -> UNICAST_WITH_CONFIRM message from MAC 8CAAB50E7E3E to MAC 78218491E47C via MAC 78218491E47C added to queue.
13:11:32.563 -> UNICAST_WITH_CONFIRM message from MAC 8CAAB50E7E3E to MAC 78218491E47C via MAC 78218491E47C sended. Status OK.
13:11:32.574 -> DELIVERY_CONFIRM_RESPONSE message from MAC 78218491E47C to MAC 8CAAB50E7E3E via MAC 78218491E47C received.
13:11:32.574 -> Message to MAC 78218491E47C ID 65451 delivered 47595 micros
13:11:33.542 -> CHECKING ROUTING TABLE... Routing to MAC 78218491E47C not found. Target is 78218491E47C.
13:11:33.542 -> UNICAST_WITH_CONFIRM message from MAC 8CAAB50E7E3E to MAC 78218491E47C via MAC 78218491E47C added to queue.
13:11:33.542 -> UNICAST_WITH_CONFIRM message from MAC 8CAAB50E7E3E to MAC 78218491E47C via MAC 78218491E47C sended. Status OK.`

**Receiver serial output:**
`13:11:29.517 -> UNICAST_WITH_CONFIRM message from MAC 8CAAB50E7E3E to MAC 78218491E47C via MAC 8CAAB50E7E3E received.
13:11:29.517 -> Unicast message from MAC 8CAAB50E7E3E received.
13:11:29.517 -> Message: Hello 2|704
13:11:29.517 -> CHECKING ROUTING TABLE... Routing to MAC 8CAAB50E7E3E not found. Target is 8CAAB50E7E3E.
13:11:29.549 -> DELIVERY_CONFIRM_RESPONSE message from MAC 78218491E47C to MAC 8CAAB50E7E3E via MAC 8CAAB50E7E3E added to queue.
13:11:29.549 -> DELIVERY_CONFIRM_RESPONSE message from MAC 78218491E47C to MAC 8CAAB50E7E3E via MAC 8CAAB50E7E3E sended. Status OK.
13:11:30.515 -> UNICAST_WITH_CONFIRM message from MAC 8CAAB50E7E3E to MAC 78218491E47C via MAC 8CAAB50E7E3E received.
13:11:30.545 -> Unicast message from MAC 8CAAB50E7E3E received.
13:11:30.545 -> Message: Hello 2|705
13:11:30.545 -> CHECKING ROUTING TABLE... Routing to MAC 8CAAB50E7E3E not found. Target is 8CAAB50E7E3E.
13:11:30.545 -> DELIVERY_CONFIRM_RESPONSE message from MAC 78218491E47C to MAC 8CAAB50E7E3E via MAC 8CAAB50E7E3E added to queue.
13:11:30.545 -> DELIVERY_CONFIRM_RESPONSE message from MAC 78218491E47C to MAC 8CAAB50E7E3E via MAC 8CAAB50E7E3E sended. Status OK.
13:11:31.541 -> UNICAST_WITH_CONFIRM message from MAC 8CAAB50E7E3E to MAC 78218491E47C via MAC 8CAAB50E7E3E received.
13:11:31.541 -> Unicast message from MAC 8CAAB50E7E3E received.
13:11:31.541 -> Message: Hello 2|706
13:11:31.541 -> CHECKING ROUTING TABLE... Routing to MAC 8CAAB50E7E3E not found. Target is 8CAAB50E7E3E.
13:11:31.541 -> DELIVERY_CONFIRM_RESPONSE message from MAC 78218491E47C to MAC 8CAAB50E7E3E via MAC 8CAAB50E7E3E added to queue.
13:11:31.573 -> DELIVERY_CONFIRM_RESPONSE message from MAC 78218491E47C to MAC 8CAAB50E7E3E via MAC 8CAAB50E7E3E sended. Status OK.
13:11:32.056 -> SEARCH_REQUEST message from MAC 8CAAB50E7E3E to MAC 78218491E47C received.
13:11:32.056 -> SEARCH_RESPONSE message from MAC 78218491E47C to MAC 8CAAB50E7E3E added to queue.
13:11:32.056 -> SEARCH_RESPONSE message from MAC 78218491E47C to MAC 8CAAB50E7E3E via MAC FFFFFFFFFFFF sended. Status OK.
13:11:32.544 -> UNICAST_WITH_CONFIRM message from MAC 8CAAB50E7E3E to MAC 78218491E47C via MAC 8CAAB50E7E3E received.
13:11:32.544 -> Unicast message from MAC 8CAAB50E7E3E received.`

**If you need more information, please let me know.**

**Thanks!**

**Comment by aZholtikov** [comment]
I do not see any problem...

Transmitter serial output:
13:11:32.024 -> SEARCH_REQUEST message from MAC 8CAAB50E7E3E to MAC 78218491E47C added to queue.
13:11:32.056 -> SEARCH_REQUEST message from MAC 8CAAB50E7E3E to MAC 78218491E47C via MAC FFFFFFFFFFFF sended. Status OK.

Receiver serial output:
13:11:32.056 -> SEARCH_REQUEST message from MAC 8CAAB50E7E3E to MAC 78218491E47C received.

The message was added to the queue, sent and received. Where in the log are the messages about SEARCH_REQUEST not received or not sent?

**Comment by Sebiferi** [comment]
Thanks for the reply! I will describe it in more detail.

13:11:31.573 -> Message to MAC 78218491E47C ID 0 delivered 50518 micros
**(Each erroneous transmission is preceded by a message with ID 0.)**
13:11:32.024 -> SEARCH_REQUEST message from MAC 8CAAB50E7E3E to MAC 78218491E47C added to queue.
13:11:32.056 -> SEARCH_REQUEST message from MAC 8CAAB50E7E3E to MAC 78218491E47C via MAC FFFFFFFFFFFF sended. Status OK.
13:11:32.056 -> Message to MAC 78218491E47C ID 32512 ---undelivered--- 517772 micros
**After each SEARCH_REQUEST message, the transmission of the next message fails.**
**After 517772 micros, the error message about failed delivery arrives. I think it's because of the timeout.**
**(myNet.setMaxWaitingTimeForRoutingInfo(500);)**

Sorry for my bad english. (Google translator)

**Comment by aZholtikov** [comment]
I see you've changed the library a bit? In that case I don't know what the problem is.
Is there the same problem if you use the unmodified library and unmodified examples?

Translated by deepl.com :-)

**Comment by Sebiferi** [comment]
> Látom, kicsit megváltoztattad a könyvtárat? Ebben az esetben nem tudom mi a probléma. Ugyanez a probléma, ha a módosítatlan könyvtárat és a módosítatlan példákat használja?
> 
> Fordította: deepl.com :-)

Yes, the problem is the same, only it appears more slowly, because in the original it sends the message every 5 seconds. And me every 1 second.

**Comment by aZholtikov** [comment]
I'll check it out over the weekend.

P.S. How many devices are in use? The example uses 3 minimum (receiver, transmitter and repeater). I have not tested on two devices (and there is no point).

**Comment by Sebiferi** [comment]
I test it on two devices. (1 receiver, 1 transmitter) I figured that if it doesn't work on two devices, it won't work on multiple devices anyway. Thanks for weekend check.

**Comment by aZholtikov** [comment]
Just in case, test it on three nodes.

Many people use this library, and all of them work on more than 20-50 devices on the network.

As an example https://forum.mysensors.org/topic/12127/zhnetwork-a-esp-now-based-mesh-network-for-esp8266-esp32-hardware

**Comment by Sebiferi** [comment]
I tested it on 3 devices. (All three devices are in the same room.)
Test1: 2 receivers, 1 transmitter.
Test2: 1 receiver 2 transmitter.
Unfortunately, the result is the same.

**Comment by aZholtikov** [comment]
One last clarification.

The SEARCH_REQUEST message is sent only if the transmitter cannot send a message to the receiver directly and retransmission is required. SEARCH_REQUEST is not sent if there are two devices located near.

Is the problem with the messages in the log or are the messages not being physically delivered?

**Comment by aZholtikov** [comment]
I didn't wait for the weekend.

The examples are tested on two devices at a distance of 1 meter. But only myNet.sendUnicastMessage("Hello world!", target, true) every second.

There are no SEARCH_REQUEST messages in the log. All messages are delivered.

I don't know what your problem is. Perhaps in the ESP modules themselves.

**Comment by aZholtikov** [comment]
And... The library is written and tested in MS Visual Studio Code, not in Arduino IDE. Perhaps the problem is in the compiler...

**Comment by Sebiferi** [comment]
I don't know what the problem could be. I tested it with many types of ESP. I didn't use VSC, only Arduino IDE. If I send my two codes (ino files), could you try them at your place?

**Comment by aZholtikov** [comment]
Ok. I will check.

**Comment by aZholtikov** [comment]
github@zh.com.ru

**Comment by Sebiferi** [comment]
Thank you very much, I sent it.
