### ISSUE TITLE
Will ESP NOW Mesh Support 1000 nodes Connected in a line(Street Light) each 50-100 meter apart

### ISSUE THREAD

**Issue by mightChamp** [aZholtikov/ZHNetwork#7]

**Comment by aZholtikov** [comment]
The 10km line formation has not been tested. Theoretically, there are no restrictions. You will have to proportionally increase the waiting time for a response.

ZHNetwork was tested on 10 devices in an area of approximately 120 square metres with 3 levels of forwarding maximum. The library is deprecated and is no longer supported.
zh_network was tested on 20 devices over an area of approximately 1 square kilometre with 5 forwarding levels maximum. About 130 devices are currently running smoothly.

**Comment by aZholtikov** [comment]
https://github.com/aZholtikov/zh_network/issues/5#issuecomment-2137297347
